# Generated by Django 3.2 on 2023-02-24 13:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_extensions.db.fields
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=16, prefix='image_', primary_key=True, serialize=False)),
                ('thickness', models.IntegerField(verbose_name='Thickness in [mm]')),
                ('corners', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Corners coordinates')),
                ('path', models.FileField(upload_to='')),
                ('type', models.CharField(default='.png', max_length=50)),
                ('file_type', models.CharField(max_length=5)),
                ('verified', models.BooleanField(default=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('-created',),
            },
        ),
    ]
